// File generated by the FlutterFire CLI, then hand-edited as a placeholder.
//
// This app does NOT require Firebase to run - by default
// (ChurchConfig.useFirebase = false) all content is served from bundled
// sample data. To connect a real Firebase project:
//
//   1. Create a project at https://console.firebase.google.com
//   2. Enable Firestore in the project
//   3. Run: dart pub global activate flutterfire_cli
//   4. Run: flutterfire configure
//      (this overwrites this file with your project's real values)
//   5. Set ChurchConfig.useFirebase = true in lib/config/church_config.dart
//
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] used by the app. These are placeholder
/// values - replace this file by running `flutterfire configure`.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
      case TargetPlatform.iOS:
      case TargetPlatform.macOS:
      case TargetPlatform.windows:
      case TargetPlatform.linux:
      case TargetPlatform.fuchsia:
        return web;
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'REPLACE_ME',
    appId: 'REPLACE_ME',
    messagingSenderId: 'REPLACE_ME',
    projectId: 'REPLACE_ME',
    authDomain: 'REPLACE_ME.firebaseapp.com',
    storageBucket: 'REPLACE_ME.appspot.com',
  );
}
